Added sample code to multiply 2 numbers along with unit tests.
padaiyal/pyProjectTemplate pull request #3
Opened 2021-10-01 23:36 UTC by aikido-sensei

2021-10-16 15:28 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers.py
> +    """
```suggestion
def multiply_2_nums(num1: int, num2: int) -> int:
    """

    :param num1: int : Number 1 used in the multiplication
    :param num2: int: Number 2 used in the multiplication
    :return: int: The result of the multiplication of num1 and num2
    """
```
```suggestion
def multiply_two_nums(num1: int, num2: int) -> int:
    """
    Multiply two numbers and return the result.
    :param num1: int : Number 1 used in the multiplication
    :param num2: int: Number 2 used in the multiplication
    :return: int: The result of the multiplication of num1 and num2
    """
```

2021-10-16 15:29 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers.py
> +    """
```suggestion
def multiply_two_nums(num1: int, num2: int) -> int:
    """
    Multiply two numbers and return the result.
    :param num1: int : Number 1 used in the multiplication
    :param num2: int: Number 2 used in the multiplication
    :return: int: The result of the multiplication of num1 and num2
    """
```
```suggestion
def multiply_2_nums(num1: int, num2: int) -> int:
    """

    :param num1: int : Number 1 used in the multiplication
    :param num2: int: Number 2 used in the multiplication
    :return: int: The result of the multiplication of num1 and num2
    """
```

2021-10-16 15:31 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers_test.py
> +        """
```suggestion
        """
        Tests the multiply_two_numbers() method for the following input combinations.
        [-2,-2] : 4
        [2,-2] : -4
        [2,2] : 4
        [3, 0] : 0
        [2, "iha"] : AttributeError
        [2, 2.5] : AttributeError
        [None, 3] : AttributeError

        """
```
```suggestion
        """
        [-2,-2] : 4
        [2,-2] : -4
        [2,2] : 4
        [3, 0] : 0
        [2, "iha"] : AttributeError
        [2, 2.5] : AttributeError
        [None, 3] : AttributeError

        """
```

2021-10-16 15:32 UTC, the-c0d3br34k3r commented
Please refer the issue number in the commit message.

2021-10-16 15:33 UTC, the-c0d3br34k3r requested changes
Reviewed. Requested changes.

2021-10-29 23:08 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers_test.py
> +    def test_multiplication(self):
```suggestion
    def test_multiplication(self) -> None:
```

2021-10-29 23:09 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers.py
> +    :return: int: The result of the multiplication of num1 and num2
Please refer the "reStructured text" example and conform to it.
https://realpython.com/documenting-python-code/#restructured-text-example

2021-10-29 23:09 UTC, the-c0d3br34k3r requested changes
Requested changes. Please squat all commits as well.

2021-11-25 00:52 UTC, the-c0d3br34k3r commented
Please refer issue in commit message.

2021-11-25 00:52 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers_test.py
> +    def test_multiplication(self):
```suggestion
    def test_multiplication(self) -> None:
```

2021-11-25 00:53 UTC, the-c0d3br34k3r commented on unit_tests/multiply_two_numbers_test.py
> +        test_inputs = {
```suggestion
        test_inputs: dict = {
```

2021-11-25 00:53 UTC, the-c0d3br34k3r requested changes
Changes have been requested.

2021-12-08 23:33 UTC, aikido-sensei commented
> Please refer the issue number in the commit message.

Done!

2021-12-08 23:34 UTC, aikido-sensei commented
> Reviewed. Requested changes.

Fixed

2021-12-08 23:34 UTC, aikido-sensei commented
> Requested changes. Please squat all commits as well.

Done!

2021-12-08 23:34 UTC, aikido-sensei commented
> Please refer issue in commit message.

Done!

2021-12-08 23:35 UTC, aikido-sensei commented
> Changes have been requested.

Corrected!

2021-12-08 23:35 UTC, the-c0d3br34k3r requested changes
Please squash all the commits into a single commit.

2021-12-11 01:27 UTC, aikido-sensei commented
> Please squash all the commits into a single commit.

Done!

2021-12-11 01:27 UTC, the-c0d3br34k3r approved these changes

2021-12-11 01:29 UTC, silvs110 approved these changes

2021-12-11 01:29 UTC, silvs110 commented on unit_tests/multiply_two_numbers.py
> +
Method's description is missing

2021-12-11 01:30 UTC, aikido-sensei commented on unit_tests/multiply_two_numbers.py
> +
Done!

2021-12-11 01:30 UTC, merged