Added Github actions for testing and linting on windows,ubuntu, macos (closes#2)
padaiyal/pyProjectTemplate pull request #4
Opened 2021-10-13 17:41 UTC by aikido-sensei

2021-10-16 00:23 UTC, silvs110 requested changes
Please change Pull Request title to the main commit title. And also link the issue2 to this PR by changing your commit's format:
```
<Title>

closes#<issue_number>
<description>
```

2021-10-16 00:23 UTC, silvs110 commented on unit_tests/multiply_two_numbers.py
> +
Add method's description (i.e what it does)

2021-10-16 00:23 UTC, silvs110 commented on unit_tests/multiply_two_numbers.py
> +    :param num2: int: Number 2 used in the multiplication
To specify a parameters type use `: type param_name: `

Example:
```
: param num1: Number 1 used in the multiplication.
: type num1: int
```

2021-10-16 00:23 UTC, silvs110 commented on unit_tests/multiply_two_numbers.py
> +    :return: int: The result of the multiplication of num1 and num2
Use `rtype` to describe return type. Example:

```
:return: The result of the multiplication of num1 and num2.
: rtype: int
```
Also, if the function raises an exception, add it to the docstring.  This [article](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html?highlight=domains#info-field-lists) gives you more information,

2021-10-16 00:23 UTC, silvs110 commented on unit_tests/multiply_two_numbers_test.py
> +        """
Add test description

2021-10-16 15:39 UTC, the-c0d3br34k3r requested changes
Please be a bit verbose about the parameters used in the commands.

2021-10-16 15:40 UTC, the-c0d3br34k3r requested changes
Reviewed. Requested changes.

2021-10-16 15:40 UTC, the-c0d3br34k3r commented on workflows/MacOs_build.yml
> +# This workflow will install Python dependencies, run tests and lint with a single version of Python on Mac OS
Please rename file to macos_build.yaml

2021-10-16 15:42 UTC, the-c0d3br34k3r commented
Please move the workflows folder to the .github folder.

2021-11-25 00:54 UTC, the-c0d3br34k3r commented
Add these actions to the .github repository and then set it up for this repo.

2021-12-08 23:27 UTC, aikido-sensei commented
> Add these actions to the .github repository and then set it up for this repo.

done

2021-12-08 23:32 UTC, the-c0d3br34k3r requested changes
Can we combine the different files for each OS into a single file like here?
https://github.com/padaiyal/jMavenProjectTemplate/blob/main/.github/workflows/maven_build.yml

2021-12-09 00:42 UTC, aikido-sensei commented
> Can we combine the different files for each OS into a single file like here? https://github.com/padaiyal/jMavenProjectTemplate/blob/main/.github/workflows/maven_build.yml

Done! I left the other files for the moment in case there is an issue with the new one.

2022-03-21 17:08 UTC, closed without merging